TARGET = libgsseap.so

SRCS = libgsseap.cpp

HEADERS = 

EXTRALIBS = -lcrypto \
	    -lltdl \
		/usr/lib/libirods_client_api_table.a \
                /usr/lib/libirods_client_plugins.a


include ../Makefile.base

